import type { Metadata } from "next";
import "./globals.css";
import HeaderMain from "@/components/ui/headerForMainPage"

//{
//  Navigation ===“/“ || navigation ===“favourites” ?(
// <header>
//  ) : (
// <sxva rame>
// )
// }

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
